### ISSUE TITLE
Examinations corrections

### ISSUE THREAD

**Issue by Tallyrald** [jan-oxymoron/project-hospital-translations#583]
[English files]
I'm not sure which english folder should I make a PR to, so I'll just write stuff down here. There are two errors I noticed:
EXM_SPINAL_FLUID_ANALYSIS_SAMPLING_DESCRIPTION: ...draining a small amount of certain amount of cerebrospinal fluid.
EXM_SPIROMETRY_DESCRIPTION: Offices / [Diagnostic] Units at Emergency dpt...

**Comment by Dysp** [comment]
I am not sure I fully understand the second issue. Except from that it doesn't really fit the LOC_ID? :/

**Comment by Dysp** [comment]
Okay, both fixed. Got it! ;)
