### ISSUE TITLE
!LOC! NOTIF Problems

### ISSUE THREAD

**Issue by TomDer22** [jan-oxymoron/project-hospital-translations#588]
Two notifications do not seem to exist in the files of the game:

!LOC! NOTIF_FINISHED_DEMO and !LOC! NOTIF_INSUR_COMPANY_NOT_AVLBL

![bug project hospital 2](https://user-images.githubusercontent.com/30384390/47617864-432ce780-dacc-11e8-8b30-e6e9ab678e0f.JPG)

![bug project hospital 1](https://user-images.githubusercontent.com/30384390/47617866-44f6ab00-dacc-11e8-9bd1-24a43c7293b1.JPG)

**Comment by pvbaekel** [comment]
**I added these lines to the script. Should I deleted the lines again?**


           <GameDBLocalizedString>      <LocID>NOTIF_FINISHED_DEMO</LocID>                   <Text>Demo beëindigd</Text>  </GameDBLocalizedString>
           <GameDBLocalizedString>      <LocID>NOTIF_FINISHED_DEMO_TEXT</LocID>              <Text>Je bent klaar met deze demo</Text>  </GameDBLocalizedString>   
    
           <GameDBLocalizedString>      <LocID>NOTIF_INSUR_COMPANY_NOT_AVLBL</LocID>         <Text>Verzekering niet beschikbaar</Text>  </GameDBLocalizedString>
           <GameDBLocalizedString>      <LocID>NOTIF_INSUR_COMPANY_NOT_AVLBL_TEXT</LocID>    <Text>Er is geen verzekeringsmaatschappij beschikbaar</Text>  </GameDBLocalizedString>
