### ISSUE TITLE
Bedürfnis-Tafel

### ISSUE THREAD

**Issue by Dantor1802** [jan-oxymoron/project-hospital-translations#655]
https://github.com/jan-oxymoron/project-hospital-translations/blob/a472d6eb51edd11876a02d45176e01e6d28d8156/localization-pack-de/StringTableDeCharacters.xml#L133

Besser:
beeinflusst durch Schmerzen, Symptome, Untersuchungen und Therapie.

Dann passt der Text auch in die 4 Zeilen rein.

**Comment by NoA51** [comment]
Ich mir das mal angeschaut und verändert. Vielen Dank für den Tipp!

**Comment by Dantor1802** [comment]
Mein Vorschlag ist ZUM TEIL übernommen worden... aber die Überschrift ist weiterhin im Erklärungstext des Tooltips vorhanden, so daß der Text über die Länge der 4 Zeilen hinausgeht.
Leute, so macht das natürlich keinen Sinn, wenn niemand die übersetzten Texte auch mal im Spiel kontrolliert. Dann kann man sich das ganze hier auch sparen. Da warte ich lieber auf den Workshop und stelle meine Textdateien dort zur Verfügung.


Hier mal eine Gegenüberstellung, wie eure Texte im Spiel aussehen im Vergleich zu meinen, so wie ich sie da oben vorgeschlagen hatte:
![texte](https://user-images.githubusercontent.com/25449553/48052772-2e75e100-e1a9-11e8-831f-d76e2f7045e0.jpg)
