### ISSUE TITLE
Und hier könnten sie einfach. ?  <!--CAMPAIGN 02-->

### ISSUE THREAD

**Issue by CityLight1976** [jan-oxymoron/project-hospital-translations#662]
https://github.com/jan-oxymoron/project-hospital-translations/blob/a472d6eb51edd11876a02d45176e01e6d28d8156/localization-pack-de/StringTableDeTutorial.xml#L184

Bitte liest den Text 

> bei

 Und hier könnten sie einfach. 

> 
..muß was geändert werden! ( Schlechte Übersetzung) 

Gruß!

**Comment by Dantor1802** [comment]
Ich habe es bei mir geändert in:
"Wir vermuten, dass er für MeDevilCare gearbeitet hat. Sie wollen einfach nicht, dass wir erfolgreich sind. Und hier könnten sie es geschafft haben."

**Comment by CityLight1976** [comment]
Wie wäre es mit:    Und das mit aller Macht.
?

**Comment by NoA51** [comment]
Habe mir das vorhin mal angeschaut, ich werde mich darum kümmern.
