### ISSUE TITLE
Orthography mistake

### ISSUE THREAD

**Issue by TFWIsaac** [jan-oxymoron/project-hospital-translations#684]
https://github.com/jan-oxymoron/project-hospital-translations/blob/fc147c0fe17e5b81270314ea59166675cce30c73/localization-pack-de/StringTableDeSymptoms.xml#L139

_Faltulenzen_ => _Flatulenzen_    
orthography mistake.

**Comment by NoA51** [comment]
Danke für deine Meldung! Wird geändert!
