### ISSUE TITLE
Validate all XML files

### ISSUE THREAD

**Issue by Dysp** [jan-oxymoron/project-hospital-translations#699]
We've had an issue with a few missing closing text tags. Let's go through them all.

- [x] English
- [x] CZ
- [x] DA
- [x] DE
- [x] ES
- [x] ET
- [x] FI
- [x] FR
- [x] HE
- [x] HU
- [x] IT
- [x] JA
- [x] KR
- [x] LA
- [x] NL
- [x] PL
- [x] PTBR
- [x] RO
- [x] RU
- [x] SWE
- [x] TR
- [x] ZH-HANS
- [x] ZHTW

**Comment by pvbaekel** [comment]
Dutch Translators encountered an issue with the NL-Symptoms-files. We fixed the file.

**Comment by NoA51** [comment]
HE is not translated, no Files

All other languages validated and fixed.
