### ISSUE TITLE
Typo in Characters

### ISSUE THREAD

**Issue by Tallyrald** [jan-oxymoron/project-hospital-translations#8]
There is a typo in the english 'StringTableEnCharacters.xml' file.

Line: 49
LocID: PERK_LONG_COMMUTE_DESCRIPTION
Wrong line: Long drive from home. Can be ofter late for work.
Correct line: Long drive from home. Can be often late for work.

**Comment by Dysp** [comment]
There are maaaannnyyyy. Unfortunately we haven't proofread the English version yet. We will create a forum post about this tomorrow

@jan-oxymoron

**Comment by Tallyrald** [comment]
Oh I didn't know that, thanks for letting us know!

**Comment by Dysp** [comment]
There is a post on the forum now
