### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by bruceCzK** [jan-oxymoron/project-hospital-translations#858]
https://github.com/jan-oxymoron/project-hospital-translations/blob/37374d29a4690501a9be9890f90023f67e85e0b7/localization-base-english/StringTableEnAchievements.xml#L26

Here's an leading sentence 'The walls have eyes', I think it's not a valid syntax in xml.
Is it been mistakenly added or is it a special syntax.

**Comment by Dysp** [comment]
That is a mistake. I'll correct it.
